FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt
RUN pip install prometheus_client

COPY . /app

EXPOSE 8001

CMD ["uvicorn", "app2.main:app", "--host", "0.0.0.0", "--port", "8001"]
