FROM nginx:1.21.6-alpine

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./nginx/sites-available/links.html /usr/share/nginx/html/
COPY ./nginx/ssl/nginx.crt /etc/nginx/ssl/nginx.crt
COPY ./nginx/ssl/nginx.key.nopass /etc/nginx/ssl/nginx.key

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
