apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server-1
  template:
    metadata:
      labels:
        app: redis-server-1
    spec:
      containers:
        - name: redis-server-1
          image: redis:alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-server-1
spec:
  selector:
    app: redis-server-1
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server-2
  template:
    metadata:
      labels:
        app: redis-server-2
    spec:
      containers:
        - name: redis-server-2
          image: redis:alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-server-2
spec:
  selector:
    app: redis-server-2
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
