---
- name: Install packages on all servers
  hosts: all
  become: yes
  tasks:
    - name: Install the required packages
      apt:
        name:
          - curl
          - git
          - vim
        state: present
        update_cache: yes
