---
all:
  children:
    staging_servers_web:
      hosts:
        linux-1:
          ansible_host: 192.168.49.1
          ansible_user: newuser
          ansible_password: 7489
          ansible_become_password: 7489
          ansible_connection: ssh
          ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

    staging_servers_bd:
      hosts:
        linux-2:
          ansible_host: 172.21.0.1
          ansible_user: newuser
          ansible_password: 7489
          ansible_become_password: 7489
          ansible_connection: ssh
          ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

        linux-3:
          ansible_host: 192.168.100.8
          ansible_user: newuser
          ansible_password: 7489
          ansible_become_password: 7489
          ansible_connection: ssh
          ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

    staging_servers_all:
      children:
        staging_servers_web:
        staging_servers_bd:
