name: Build and Push Docker image

on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}"
          docker-compose -f docker-compose.yml build  # Строим образы с использованием docker-compose
          docker-compose -f docker-compose.yml push   # Пушим образы в DockerHub

      - name: Clean up containers
        run: |
          docker-compose down
