name: CI

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s app/tests
  
      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Проверка версии Docker Compose

      - name: Build Docker image with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
          
      - name: Push Docker image to DockerHub
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}"
          docker-compose -f docker-compose.yml push  # Пушим образ в DockerHub

      - name: Run Docker Compose (detached)
        run: |
          docker-compose -f docker-compose.yml up --build -d
        
      - name: Clean up containers
        run: |
          docker-compose down  # Останавливаем и удаляем контейнеры
